Refactored Bash Script to inline

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -111,7 +111,10 @@ runs:
 
     - name: Wait for a VPN connection with default test ping ip host
       if: inputs.test-ping-ip-host != null
-      run: ./test-ping.sh ${{ inputs.test-ping-ip-host }}
+      run: | 
+        COUNTER=0; while [ $COUNTER -lt 10 ]; do output=$(ping -c 1 -W 1 "${{ inputs.test-ping-ip-host }}"); \
+        if [ $? -eq 0 ]; then echo "Ping was successful."; exit 0; else echo "Ping to ${{ inputs.test-ping-ip-host }} failed."; \
+        COUNTER=$((COUNTER+1)); sleep 1; fi; done; echo "Ping timed out"; exit 1
       shell: bash
 
     - name: Show VPN log
